import TabGroup from "@/components/TabGroup";
import "./globals.css";
import { Inter } from "next/font/google";
import { CHARTS_NAME } from "@/constant/namechart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex justify-center mt-10 px-10">
          <div className="p-5 border-[1px] rounded-lg w-full">
            <TabGroup
              items={[
                { name: "Home", slug: "/" },
                ...CHARTS_NAME.filter((item) => item.parent === null),
              ]}
            />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
